### ISSUE TITLE
三百部电视剧，会漏掉几部没有生成strm文件，还有三个文件夹名字乱码，不知道是否是我哪里设置错了，多为TS格式的视频

### ISSUE THREAD

**Issue by qq1620** [907739769/alist-strm#2]
三百部电视剧，会漏掉几部没有生成strm文件，还有三个文件夹名字乱码，不知道是否是我哪里设置错了，多为TS格式的视频

**Comment by 907739769** [comment]
截图看下目录文件结构，alist上面的截图和本地生成的文件目录截图

**Comment by 907739769** [comment]
.ts的文件我没有处理

**Comment by 907739769** [comment]
> .ts的文件我没有处理

增加支持了 拉下最新镜像 @qq1620

**Comment by qq1620** [comment]
文件数目现在对的上了，没有漏了
![QQ截图20240718233416](https://github.com/user-attachments/assets/3730a528-f903-4b90-96a4-d9f840ffdeb2)就是文件夹的名字有点怪，左边是抓取以后在unraid文件管理里面看文件名正常，右边是我用windows通过SMB查看有三个文件名变了，但不影响识别，可能是我系统BUG吧
