### ISSUE TITLE
生成strm文件正常，Emby正常刮削元数据，但是无法播放

### ISSUE THREAD

**Issue by johnsyoun** [907739769/alist-strm#4]
群晖系统。
生成strm文件正常，Emby正常刮削元数据，但是无法播放。
请教问题出在哪里呢？

docker-compose.yaml内容如下：
version: '3.9'
services:
  app:
    container_name: alist-strm
    image: jacksaoding/alist-strm:latest
    network_mode: host
    environment:
      TZ: Asia/Shanghai
      alistServerUrl: http://192.168.10.128:5244
      alistServerToken:  # 已正确添加alist-token
      alistScanPath: /ali
      slowMode: 0
      isDownSub: 1
      runAfterStartup: 1
    volumes:
      - /volume5/CloudNAS/00AlistStrm:/data
    
生成的strm文件内容如下：
http://192.168.10.128:5244/d/ali9528/%E7%94%B5%E5%BD%B1%E7%B3%BB%E5%88%97/%E9%9C%8D%E6%AF%94%E7%89%B9%E4%BA%BA%EF%BC%88%E7%B3%BB%E5%88%97%EF%BC%894K%20REMUX/%E9%9C%8D%E6%AF%94%E7%89%B9%E4%BA%BA1%EF%BC%9A%E6%84%8F%E5%A4%96%E4%B9%8B%E6%97%85%20%282012%29/The.Hobbit.An.Unexpected.Journey.2012.EXTENDED.2160p.BluRay.REMUX.HEVC.DTS-HD.MA.TrueHD.7.1.Atmos-FGT.mkv

**Comment by 907739769** [comment]
alist能正常播放没  我这只是生成strm文件 可以看alist和emby日志  挂载的是什么网盘
